// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS592MeOcr5zuFbrQ_lavml-i_Wkr55do',
    appId: '1:827840523652:web:b0696725454a1fadce81d1',
    messagingSenderId: '827840523652',
    projectId: 'smart-tasks-ai',
    authDomain: 'smart-tasks-ai.firebaseapp.com',
    storageBucket: 'smart-tasks-ai.firebasestorage.app',
    measurementId: 'G-YNF98C9WQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX3oYSCa404iHwrVwGA2gnxu88fzJQGK8',
    appId: '1:827840523652:android:a21c6dd6c847df6ece81d1',
    messagingSenderId: '827840523652',
    projectId: 'smart-tasks-ai',
    storageBucket: 'smart-tasks-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBapeowUkqp7mXH-SmLecZ6KOGZjDq7ok',
    appId: '1:827840523652:ios:0b3886c51fd0fb03ce81d1',
    messagingSenderId: '827840523652',
    projectId: 'smart-tasks-ai',
    storageBucket: 'smart-tasks-ai.firebasestorage.app',
    iosBundleId: 'com.example.smartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBapeowUkqp7mXH-SmLecZ6KOGZjDq7ok',
    appId: '1:827840523652:ios:0b3886c51fd0fb03ce81d1',
    messagingSenderId: '827840523652',
    projectId: 'smart-tasks-ai',
    storageBucket: 'smart-tasks-ai.firebasestorage.app',
    iosBundleId: 'com.example.smartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS592MeOcr5zuFbrQ_lavml-i_Wkr55do',
    appId: '1:827840523652:web:7c005a0a31cf3334ce81d1',
    messagingSenderId: '827840523652',
    projectId: 'smart-tasks-ai',
    authDomain: 'smart-tasks-ai.firebaseapp.com',
    storageBucket: 'smart-tasks-ai.firebasestorage.app',
    measurementId: 'G-PZMQ6BCCZS',
  );
}
